fix: nginx reload 오류해결

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -209,13 +209,26 @@ jobs:
             sudo cp "$NGINX_CONFIG_PATH" "$NGINX_CONFIG_PATH.bak"
             sudo sed -i "s/\(proxy_pass http:\/\/127.0.0.1:\)[0-9]\+/\1$TARGET_PORT/" "$NGINX_CONFIG_PATH"
             
-            if ! sudo nginx -t && sudo systemctl reload nginx; then
-              echo "Nginx reload failed. Reverting to backup configuration."
+            echo "Testing NGINX configuration..."
+            if sudo nginx -t; then
+              echo "NGINX configuration test successful. Reloading NGINX..."
+              # 테스트 성공 시에만 리로드 시도
+              if ! sudo systemctl reload nginx; then
+                echo "NGINX reload failed. Reverting to backup configuration."
+                sudo mv "$NGINX_CONFIG_PATH.bak" "$NGINX_CONFIG_PATH"
+                sudo nginx -t && sudo systemctl reload nginx
+                docker compose rm -f $NEW_CONTAINER_NAME
+                exit 1
+              fi
+            else
+            # 테스트 실패 시 바로 복구
+              echo "NGINX configuration test failed. Reverting to backup configuration."
               sudo mv "$NGINX_CONFIG_PATH.bak" "$NGINX_CONFIG_PATH"
               sudo nginx -t && sudo systemctl reload nginx
               docker compose rm -f $NEW_CONTAINER_NAME
               exit 1
             fi
+            echo "NGINX reloaded successfully."
             
             echo "Nginx switch successful. Checking application health via Nginx..."
             if ! wait_for_nginx_health; then
